[package]
name = "rslint-staged"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.14.2"
serde_json = "1.0"
globset = "0.4.8"
rayon = "1.5.1"